### ISSUE TITLE
Resource count not working

### ISSUE THREAD

**Issue by Orionox** [ardittristan/5eSheet-resourcesPlus#39]
Regardless of what I place in the resource count section, all of my character sheets show only 4 resources.

**Comment by KellethDregar** [comment]
Yeah looks like it broke recently, it doesn't retain the resource count and when applied it always has the maximum amount of 20.

I am personally on Foundry v11.313 and Dnd5e v2.4.1

![image](https://github.com/ardittristan/5eSheet-resourcesPlus/assets/79947702/b8887130-c7f1-40e3-9870-7cfbde0e55f4)
![image](https://github.com/ardittristan/5eSheet-resourcesPlus/assets/79947702/77198e54-d380-4a0e-8a5a-29ba0bc20fef)

**Comment by GMToolbox** [comment]
Ya. Same issue. Resource count not working. Always seeing 20

**Comment by ardittristan** [comment]
I'm taking a look at it! sorry for the delay

**Comment by ardittristan** [comment]
should be fixed

**Comment by TrexMonster** [comment]
Same problem.
Names and count of resources are not changed.
(for all resources starting from 4).
dnd 3.0.3, foundry 11.315

**Comment by MotoMoto1234** [comment]
This issue is not fixed, but its not caused on its own.  Its caused by an interaction with DAE and 5e resources plus, and looks ugliest in tidy5e, but shows its issue in the legacy sheet also.  Kgar found the issue most directly in the midi discord yesterday.  5eresources plus is registering its schema in a bad place so other modules poorly interact with it.  Tposney has been made aware, not sure if he's going to fix it on dae's side or submit a pr for you.

**Comment by MotoMoto1234** [comment]
This should be fixed with DAE version 11.3.11.
